In [1]:
# installing all packages and dependencies
!pip install bertopic[all]

Requirement already satisfied: bertopic[all] in /usr/local/lib/python3.7/dist-packages (0.8.1)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (1.20.3)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (1.2.0)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (0.5.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (4.41.1)
Requirement already satisfied: hdbscan>=0.8.27 in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (0.8.27)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (0.22.2.post1)
Requirement already satisfied: plotly<4.14.3,>=4.7.0 in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (4.14.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (1.1.5)
Requirement already satisfied: torch<1.7.1,>=1.4.0; extra == "all" in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (1.7.0)
Requirement already satisfied: flair==0.7; extra == "all" in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (0.7)
Requirement already satisfied: tensorflow; extra == "all" in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (2.5.0)
Requirement already satisfied: tensorflow-hub; extra == "all" in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (0.12.0)
Requirement already satisfied: gensim>=3.6.0; extra == "all" in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (3.6.0)
Requirement already satisfied: tensorflow-text; extra == "all" in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (2.5.0)
Requirement already satisfied: transformers==3.5.1; extra == "all" in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (3.5.1)
Requirement already satisfied: spacy>=3.0.1; extra == "all" in /usr/local/lib/python3.7/dist-packages (from bertopic[all]) (3.0.6)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from sentence-transformers>=0.4.1->bertopic[all]) (1.4.1)
Requirement already satisfied: torchvision in /usr/local/lib/python3.7/dist-packages (from sentence-transformers>=0.4.1->bertopic[all]) (0.9.1+cu101)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.7/dist-packages (from sentence-transformers>=0.4.1->bertopic[all]) (0.1.95)
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (from sentence-transformers>=0.4.1->bertopic[all]) (3.2.5)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.7/dist-packages (from umap-learn>=0.5.0->bertopic[all]) (0.5.2)
Requirement already satisfied: numba>=0.49 in /usr/local/lib/python3.7/dist-packages (from umap-learn>=0.5.0->bertopic[all]) (0.51.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from hdbscan>=0.8.27->bertopic[all]) (1.15.0)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.7/dist-packages (from hdbscan>=0.8.27->bertopic[all]) (1.0.1)
Requirement already satisfied: cython>=0.27 in /usr/local/lib/python3.7/dist-packages (from hdbscan>=0.8.27->bertopic[all]) (0.29.23)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly<4.14.3,>=4.7.0->bertopic[all]) (1.3.3)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.1.5->bertopic[all]) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.1.5->bertopic[all]) (2.8.1)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from torch<1.7.1,>=1.4.0; extra == "all"->bertopic[all]) (0.16.0)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.7/dist-packages (from torch<1.7.1,>=1.4.0; extra == "all"->bertopic[all]) (0.6)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch<1.7.1,>=1.4.0; extra == "all"->bertopic[all]) (3.7.4.3)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (2019.12.20)
Requirement already satisfied: janome in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (0.4.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (4.2.6)
Requirement already satisfied: ftfy in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (6.0.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (0.8.9)
Requirement already satisfied: mpld3==0.3 in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (0.3)
Requirement already satisfied: bpemb>=0.3.2 in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (0.3.3)
Requirement already satisfied: sqlitedict>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (1.7.0)
Requirement already satisfied: segtok>=1.5.7 in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (1.5.10)
Requirement already satisfied: deprecated>=1.2.4 in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (1.2.12)
Requirement already satisfied: hyperopt>=0.1.1 in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (0.1.2)
Requirement already satisfied: matplotlib>=2.2.3 in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (3.2.2)
Requirement already satisfied: gdown in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (3.6.4)
Requirement already satisfied: langdetect in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (1.0.9)
Requirement already satisfied: konoha<5.0.0,>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from flair==0.7; extra == "all"->bertopic[all]) (4.6.5)
Requirement already satisfied: tensorflow-estimator<2.6.0,>=2.5.0rc0 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (2.5.0)
Requirement already satisfied: gast==0.4.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (0.4.0)
Requirement already satisfied: h5py~=3.1.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (3.1.0)
Requirement already satisfied: wheel~=0.35 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (0.36.2)
Requirement already satisfied: keras-nightly~=2.5.0.dev in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (2.5.0.dev2021032900)
Requirement already satisfied: absl-py~=0.10 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (0.12.0)
Requirement already satisfied: grpcio~=1.34.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (1.34.1)
Requirement already satisfied: tensorboard~=2.5 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (2.5.0)
Requirement already satisfied: termcolor~=1.1.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (1.1.0)
Requirement already satisfied: keras-preprocessing~=1.1.2 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (1.1.2)
Requirement already satisfied: flatbuffers~=1.12.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (1.12)
Requirement already satisfied: astunparse~=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (1.6.3)
Requirement already satisfied: wrapt~=1.12.1 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (1.12.1)
Requirement already satisfied: opt-einsum~=3.3.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (3.3.0)
Requirement already satisfied: protobuf>=3.9.2 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (3.12.4)
Requirement already satisfied: google-pasta~=0.2 in /usr/local/lib/python3.7/dist-packages (from tensorflow; extra == "all"->bertopic[all]) (0.2.0)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from gensim>=3.6.0; extra == "all"->bertopic[all]) (5.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers==3.5.1; extra == "all"->bertopic[all]) (2.23.0)
Requirement already satisfied: tokenizers==0.9.3 in /usr/local/lib/python3.7/dist-packages (from transformers==3.5.1; extra == "all"->bertopic[all]) (0.9.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers==3.5.1; extra == "all"->bertopic[all]) (3.0.12)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from transformers==3.5.1; extra == "all"->bertopic[all]) (20.9)
Requirement already satisfied: sacremoses in /usr/local/lib/python3.7/dist-packages (from transformers==3.5.1; extra == "all"->bertopic[all]) (0.0.45)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.4 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (3.0.5)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (0.8.2)
Requirement already satisfied: typer<0.4.0,>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (0.3.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (2.11.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.1 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (2.4.1)
Requirement already satisfied: thinc<8.1.0,>=8.0.3 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (8.0.3)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (2.0.5)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (0.4.1)
Requirement already satisfied: pathy>=0.3.5 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (0.5.2)
Requirement already satisfied: pydantic<1.8.0,>=1.7.1 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (1.7.4)
Requirement already satisfied: catalogue<2.1.0,>=2.0.3 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (2.0.4)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (3.0.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (57.0.0)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy>=3.0.1; extra == "all"->bertopic[all]) (1.0.5)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.7/dist-packages (from torchvision->sentence-transformers>=0.4.1->bertopic[all]) (7.1.2)
Requirement already satisfied: llvmlite>=0.30 in /usr/local/lib/python3.7/dist-packages (from pynndescent>=0.5->umap-learn>=0.5.0->bertopic[all]) (0.34.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from ftfy->flair==0.7; extra == "all"->bertopic[all]) (0.2.5)
Requirement already satisfied: pymongo in /usr/local/lib/python3.7/dist-packages (from hyperopt>=0.1.1->flair==0.7; extra == "all"->bertopic[all]) (3.11.4)
Requirement already satisfied: networkx in /usr/local/lib/python3.7/dist-packages (from hyperopt>=0.1.1->flair==0.7; extra == "all"->bertopic[all]) (2.5.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2.3->flair==0.7; extra == "all"->bertopic[all]) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2.3->flair==0.7; extra == "all"->bertopic[all]) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.2.3->flair==0.7; extra == "all"->bertopic[all]) (1.3.1)
Requirement already satisfied: importlib-metadata<4.0.0,>=3.7.0 in /usr/local/lib/python3.7/dist-packages (from konoha<5.0.0,>=4.0.0->flair==0.7; extra == "all"->bertopic[all]) (3.10.1)
Requirement already satisfied: overrides<4.0.0,>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from konoha<5.0.0,>=4.0.0->flair==0.7; extra == "all"->bertopic[all]) (3.1.0)
Requirement already satisfied: cached-property; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from h5py~=3.1.0->tensorflow; extra == "all"->bertopic[all]) (1.5.2)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (1.8.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (1.30.0)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (1.0.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (0.4.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (3.3.4)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (0.6.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers==3.5.1; extra == "all"->bertopic[all]) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers==3.5.1; extra == "all"->bertopic[all]) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers==3.5.1; extra == "all"->bertopic[all]) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers==3.5.1; extra == "all"->bertopic[all]) (2.10)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers==3.5.1; extra == "all"->bertopic[all]) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->spacy>=3.0.1; extra == "all"->bertopic[all]) (2.0.1)
Requirement already satisfied: zipp>=0.5; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from catalogue<2.1.0,>=2.0.3->spacy>=3.0.1; extra == "all"->bertopic[all]) (3.4.1)
Requirement already satisfied: decorator<5,>=4.3 in /usr/local/lib/python3.7/dist-packages (from networkx->hyperopt>=0.1.1->flair==0.7; extra == "all"->bertopic[all]) (4.4.2)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in /usr/local/lib/python3.7/dist-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (4.2.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (1.3.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.7/dist-packages (from rsa<5,>=3.1.4; python_version >= "3.6"->google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow; extra == "all"->bertopic[all]) (3.1.0)

In [2]:
from bertopic import BERTopic
import pandas as pd

In [3]:
# importing local file dataset and creating different document filters to pass into BERTopic model
# filtered_smaller_sample.csv can be found on our github repo

df = pd.read_csv('filtered_smaller_sample.csv', engine="python")
docs = df['data_a']
docs_filter = df['filtered_sentence']
docs_combined = df['combined']

In [ ]:
# extracting topic from our docs - using only the answers
topic_model_answers_only = BERTopic()
topics, _ = topic_model_answers_only.fit_transform(docs)

In [ ]:
# checking the number of topics generated, should equal total number of rows 536
len(topics)

536

In [ ]:
# getting all topic information 
topic_model_answers_only.get_topic_info()

   Topic  Count                                  Name
0     -1    209                   -1_this_your_it_you
1      0    107                   0_the_his_film_name
2      1    100            1_san_washington_tour_city
3      2     74             2_john_michael_lewis_hart
4      3     36  3_queen_elizabeth_cleopatra_victoria
5      4     10                   4_turtle_he_him_his

In [ ]:
# extracting topic from our second set of docs - using only the filtered sentences (stop words pre-removed, includes both questions and answers)
topic_model_filtered = BERTopic()
topics, _ = topic_model_filtered.fit_transform(docs_filter)

In [ ]:
# accessing information from filtered topic 
topic_model_filtered.get_topic_info()

   Topic  Count                           Name
0     -1    504      -1_state_name_world_first
1      0     16     0_exile_evian_events_event
2      1     16  1_language_greek_word_example

In [ ]:
# extracting topic from our second set of docs - using only combined questions and answers, with stop words
topic_model_combined = BERTopic()
topics, _ = topic_model_combined.fit_transform(docs_combined)

In [ ]:
topic_model_combined.get_topic_info()

   Topic  Count                                   Name
0     -1    507                        -1_the_in_of_on
1      0     16            0_zoo_exiled_exile_everlast
2      1     13  1_language_policy_curriculum_syllabus

In [25]:
# testing combined docs with an nr_topics = 20
topic_model_combined_20 = BERTopic(min_topic_size=8, embedding_model="paraphrase-MiniLM-L6-v2")
topics, _ = topic_model_combined_20.fit_transform(docs_combined)

topic_model_combined_20.get_topic_info()

    Topic  Count                                     Name
0      -1    115                      -1_com_his_href_www
1       0     56                0_let_pill_emoticons_take
2       1     55                1_authors_poets_art_wrote
3       2     47        2_city_geography_island_etropolis
4       3     28       3_warhol_company_business_industry
5       4     23  4_state_college_superlatives_california
6       5     21                5_drama_film_movie_cinema
7       6     20         6_science_measuring_gases_energy
8       7     19         7_sports_sportsmen_athletes_espn
9       8     19     8_collective_animal_mythology_angels
12     10     16           10_music_entertainment_tv_tour
10     11     16        11_evergreen_everett_events_event
11      9     16        9_language_greek_kayak_palindrome
13     12     15             12_royal_queen_name_princess
14     13     12              13_theatre_elm_books_potter
15     14     12       14_consonants_homophonic_pairs_row
16     15     12                15_flag_flags_nation_cuba
17     16     12          16_peach_multiply_fruitful_tree
18     17     11     17_airline_travel_bus_transportation
19     18     11              18_disney_voice_singer_band

In [26]:
topic_model_combined_20.topics

{-1: [('com', 0.016618828219322843),
  ('his', 0.015787865508182748),
  ('href', 0.015649930471539075),
  ('www', 0.015649930471539075),
  ('archive', 0.015649930471539075),
  ('old', 0.013591198328320302),
  ('country', 0.013295062575458275),
  ('from', 0.012794288897787399),
  ('history', 0.012519214365904),
  ('exile', 0.012510651158528382)],
 0: [('let', 0.03982132224053963),
  ('pill', 0.026308628180492705),
  ('emoticons', 0.026308628180492705),
  ('take', 0.024276791002828375),
  ('it', 0.023803567827908944),
  ('slang', 0.022124890714994207),
  ('rhymes', 0.02104690254439416),
  ('word', 0.019674496002545182),
  ('can', 0.018776353610839885),
  ('medicine', 0.016593668036245658)],
 1: [('authors', 0.03469994590687873),
  ('poets', 0.026860103740379726),
  ('art', 0.02573604975274745),
  ('wrote', 0.02478567564777052),
  ('literature', 0.02258866770901998),
  ('artists', 0.01800567614225246),
  ('novel', 0.01800567614225246),
  ('governor', 0.01800567614225246),
  ('book', 0.016116062244227836),
  ('robert', 0.016116062244227836)],
 2: [('city', 0.06433301189078505),
  ('geography', 0.04568450670532249),
  ('island', 0.041631382342382346),
  ('etropolis', 0.0353628963205324),
  ('tourism', 0.028290317056425922),
  ('travel', 0.024473520531087485),
  ('kingdom', 0.02230447586690163),
  ('islands', 0.02230447586690163),
  ('country', 0.021604476685119698),
  ('history', 0.020343723344594)],
 3: [('warhol', 0.07316150959894317),
  ('company', 0.06716708642494722),
  ('business', 0.056756281271553584),
  ('industry', 0.04911043846936043),
  ('organizations', 0.04310449296944754),
  ('store', 0.034359066709098225),
  ('mall', 0.034359066709098225),
  ('30s', 0.030753238776632413),
  ('firm', 0.024814115569711748),
  ('fashion', 0.02290604447273215)],
 4: [('state', 0.15385273121854456),
  ('college', 0.06106688491243107),
  ('superlatives', 0.05514821299607078),
  ('california', 0.04227227615084189),
  ('skiing', 0.029519279980586247),
  ('northwestern', 0.02669873194209492),
  ('valley', 0.024645744052939657),
  ('texas', 0.024645744052939657),
  ('colorado', 0.02318912596457621),
  ('washington', 0.021136138075420946)],
 5: [('drama', 0.05778128417360202),
  ('film', 0.05536322639118882),
  ('movie', 0.05536322639118882),
  ('cinema', 0.048592598175106645),
  ('queens', 0.046225027338881605),
  ('films', 0.036444448631329986),
  ('played', 0.03466877050416121),
  ('tv', 0.03324067262671062),
  ('television', 0.02797347245922412),
  ('movies', 0.023112513669440803)],
 6: [('science', 0.15804199624731072),
  ('measuring', 0.06502550487596405),
  ('gases', 0.05448732593793562),
  ('energy', 0.03935074297435632),
  ('measured', 0.03935074297435632),
  ('ph', 0.03935074297435632),
  ('water', 0.03115214380519132),
  ('scientists', 0.022261741563894374),
  ('igneous', 0.022261741563894374),
  ('carbon', 0.022261741563894374)],
 7: [('sports', 0.06415271154364434),
  ('sportsmen', 0.057934957801723294),
  ('athletes', 0.057934957801723294),
  ('espn', 0.05551046901456964),
  ('sport', 0.04440837521165571),
  ('team', 0.028047869992360353),
  ('player', 0.028047869992360353),
  ('soccer', 0.028047869992360353),
  ('jordan', 0.02589114069391267),
  ('olympians', 0.02436091690427554)],
 8: [('collective', 0.07384252248626427),
  ('animal', 0.07384252248626427),
  ('mythology', 0.059074017989011414),
  ('angels', 0.059074017989011414),
  ('dog', 0.049500350343616085),
  ('kennel', 0.033000233562410726),
  ('wings', 0.033000233562410726),
  ('shepherd', 0.0202242262343176),
  ('bucephalus', 0.0202242262343176),
  ('captivity', 0.0202242262343176)],
 9: [('language', 0.33836867353084943),
  ('greek', 0.16753039644154552),
  ('kayak', 0.12588451164971334),
  ('palindrome', 0.09091378549247839),
  ('syllabus', 0.051432299475204245),
  ('curriculum', 0.051432299475204245),
  ('paddles', 0.051432299475204245),
  ('reversible', 0.051432299475204245),
  ('meteorite', 0.051432299475204245),
  ('crater', 0.051432299475204245)],
 10: [('music', 0.34459170772014674),
  ('entertainment', 0.29817051927825977),
  ('tv', 0.1342685740743204),
  ('tour', 0.13085292508582289),
  ('mozart', 0.08523066770176703),
  ('comedian', 0.08523066770176703),
  ('composer', 0.08523066770176703),
  ('edwards', 0.08523066770176703),
  ('abc', 0.08523066770176703),
  ('cbs', 0.08523066770176703)],
 11: [('evergreen', 0.0),
  ('everett', 0.0),
  ('events', 0.0),
  ('event', 0.0),
  ('eve', 0.0),
  ('etropolis', 0.0),
  ('ethics', 0.0),
  ('fairbanks', 0.0),
  ('fair', 0.0),
  ('facts', 0.0)],
 12: [('royal', 0.09530564543140722),
  ('queen', 0.09178622351754288),
  ('name', 0.08418993425862747),
  ('princess', 0.06667855411582989),
  ('diana', 0.048155247110171204),
  ('prince', 0.048155247110171204),
  ('british', 0.035495024634190464),
  ('windsor', 0.027242679174080783),
  ('gowns', 0.027242679174080783),
  ('margaret', 0.027242679174080783)],
 13: [('theatre', 0.17993048577136367),
  ('elm', 0.051432299475204245),
  ('books', 0.051432299475204245),
  ('potter', 0.051432299475204245),
  ('shakespeare', 0.051432299475204245),
  ('faust', 0.051432299475204245),
  ('wizard', 0.051432299475204245),
  ('colchian', 0.051432299475204245),
  ('mephistopheles', 0.051432299475204245),
  ('lines', 0.051432299475204245)],
 14: [('consonants', 0.1414515852821296),
  ('homophonic', 0.1414515852821296),
  ('pairs', 0.1414515852821296),
  ('row', 0.1414515852821296),
  ('words', 0.04521091025111289),
  ('purr', 0.03874121259171229),
  ('inchworm', 0.03874121259171229),
  ('grasshopper', 0.03874121259171229),
  ('gourd', 0.03874121259171229),
  ('kittens', 0.03874121259171229)],
 15: [('flag', 0.2241093345181692),
  ('flags', 0.11932866834257452),
  ('nation', 0.04625438209266444),
  ('cuba', 0.04625438209266444),
  ('country', 0.029184994820249412),
  ('germany', 0.026167310259314437),
  ('officially', 0.026167310259314437),
  ('colors', 0.026167310259314437),
  ('nicknamed', 0.026167310259314437),
  ('1844', 0.026167310259314437)],
 16: [('peach', 0.300291938207348),
  ('multiply', 0.17855364043809802),
  ('fruitful', 0.17855364043809802),
  ('tree', 0.07979564672878003),
  ('grow', 0.048902842123964695),
  ('peaches', 0.048902842123964695),
  ('iris', 0.048902842123964695),
  ('growth', 0.048902842123964695),
  ('blossoms', 0.048902842123964695),
  ('fruit', 0.048902842123964695)],
 17: [('airline', 0.14908525963912989),
  ('travel', 0.11217030243415096),
  ('bus', 0.06277380426861603),
  ('transportation', 0.05794683869589978),
  ('trip', 0.0355127782090696),
  ('ford', 0.0355127782090696),
  ('passenger', 0.0355127782090696),
  ('vehicles', 0.0355127782090696),
  ('buy', 0.0355127782090696),
  ('roped', 0.0355127782090696)],
 18: [('disney', 0.1379492947572483),
  ('voice', 0.12277609617340109),
  ('singer', 0.04772092598485865),
  ('band', 0.044900513509841186),
  ('who', 0.0326185236226317),
  ('sheena', 0.02924581734864555),
  ('willie', 0.02924581734864555),
  ('tedder', 0.02924581734864555),
  ('shrek', 0.02924581734864555),
  ('toys', 0.02924581734864555)]}

In [31]:
# testing combined docs with an nr_topics = 22
topic_model_combined_22_4 = BERTopic(min_topic_size=4, nr_topics=22, embedding_model="paraphrase-MiniLM-L6-v2")
topics, _ = topic_model_combined_22_4.fit_transform(docs_combined)

topic_model_combined_22_4.get_topic_info()

    Topic  Count                                Name
0      -1     91                -1_name_he_greek_his
1       0     48              0_flag_people_www_href
2       1     44   1_emoticons_consonants_pill_money
3       2     31     2_warhol_authors_literature_art
4       3     28                3_gov_civil_old_penn
5       4     24  4_airline_travel_devices_measuring
6       5     23        5_oscar_film_movie_cinematic
7       6     22        6_state_annual_alaska_events
8       7     21          7_peach_female_royal_queen
9       8     18    8_capital_city_etropolis_tourism
10      9     18                9_theatre_tv_thee_14
12     10     16           10_bounce_hit_skiing_game
11     11     16  11_mythology_queens_heroines_helen
13     12     15   12_sportsmen_athletes_espn_sports
14     13     15    13_mexico_kingdom_islands_resort
15     14     14   14_music_entertainment_1997_harps
16     15     14             15_meaning_from_mean_re
17     16     14      16_animal_anatomy_dog_skeletal
18     17     13       17_voice_train_musical_trains
19     18     13    18_language_know_syllabus_policy
20     19     13     19_country_african_exiled_exile
21     20     13           20_science_gases_ph_decay
22     21     12   21_company_industry_business_firm

In [32]:
topic_model_combined_22_4.topics

{-1: [('name', 0.018686479270611518),
  ('he', 0.017455325616521574),
  ('greek', 0.015312909669076079),
  ('his', 0.01528893758504579),
  ('angels', 0.014361587857446694),
  ('was', 0.014047902095905484),
  ('her', 0.013328545299396104),
  ('angel', 0.012097290861745394),
  ('american', 0.011107121082830088),
  ('who', 0.01085470973353267)],
 0: [('flag', 0.08008947895450935),
  ('people', 0.06838358773802622),
  ('www', 0.049294821505462376),
  ('href', 0.049294821505462376),
  ('flags', 0.042993295016236555),
  ('2007', 0.029112824565643017),
  ('07', 0.02764958816358262),
  ('architects', 0.026454036971491117),
  ('world', 0.025258067895334115),
  ('2010', 0.02138393934373058)],
 1: [('emoticons', 0.0348476214458376),
  ('consonants', 0.0348476214458376),
  ('pill', 0.0348476214458376),
  ('money', 0.03334083172026773),
  ('slang', 0.02935342642155742),
  ('it', 0.02729938574355063),
  ('re', 0.025768181043621823),
  ('words', 0.022089874099784794),
  ('rhymes', 0.02090857286750256),
  ('oie', 0.016968108848993402)],
 2: [('warhol', 0.06750555974235341),
  ('authors', 0.05243364808547483),
  ('literature', 0.03999734906541045),
  ('art', 0.03634451025362519),
  ('wrote', 0.03495576539031655),
  ('artists', 0.031941809585894196),
  ('poets', 0.02849028510098885),
  ('writer', 0.023120959129822094),
  ('frank', 0.021294539723929463),
  ('robert', 0.018993523400659233)],
 3: [('gov', 0.044991531280509985),
  ('civil', 0.03918738099392518),
  ('old', 0.03030716310333563),
  ('penn', 0.02636089861735506),
  ('tributes', 0.024756723492159256),
  ('was', 0.0243927411182029),
  ('john', 0.01964729561925504),
  ('adams', 0.01908123764617288),
  ('church', 0.01908123764617288),
  ('jefferson', 0.01908123764617288)],
 4: [('airline', 0.058186163050274936),
  ('travel', 0.043615090505339314),
  ('devices', 0.04054386725909952),
  ('measuring', 0.04054386725909952),
  ('measures', 0.032017108747071345),
  ('measured', 0.02467717753279089),
  ('shuttle', 0.02467717753279089),
  ('bus', 0.02467717753279089),
  ('transportation', 0.02272782605150164),
  ('smart', 0.01865427864579393)],
 5: [('oscar', 0.05923801463091812),
  ('film', 0.04106097341630937),
  ('movie', 0.04106097341630937),
  ('cinematic', 0.036086929913834664),
  ('films', 0.033890883559240914),
  ('cinema', 0.033890883559240914),
  ('hart', 0.024057953275889776),
  ('played', 0.021458331780897455),
  ('original', 0.021458331780897455),
  ('movies', 0.021458331780897455)],
 6: [('state', 0.1568533051078888),
  ('annual', 0.06360803210369077),
  ('alaska', 0.055112577023939825),
  ('events', 0.04608264693930437),
  ('festival', 0.028048376649292373),
  ('fair', 0.028048376649292373),
  ('bears', 0.025832720320832465),
  ('texas', 0.025832720320832465),
  ('washington', 0.02204503080957593),
  ('california', 0.02204503080957593)],
 7: [('peach', 0.11329308727930561),
  ('female', 0.06779038898627571),
  ('royal', 0.06485917424682307),
  ('queen', 0.06238086749718869),
  ('name', 0.04811181216473145),
  ('princess', 0.045601811756067596),
  ('prince', 0.03300870049402254),
  ('diana', 0.03300870049402254),
  ('british', 0.024093624216724206),
  ('skirt', 0.018733119316335853)],
 8: [('capital', 0.1137393517478281),
  ('city', 0.1030406511619647),
  ('etropolis', 0.08971408925417765),
  ('tourism', 0.07177127140334212),
  ('bucharest', 0.04368385469634472),
  ('saigon', 0.04368385469634472),
  ('rome', 0.04368385469634472),
  ('belize', 0.04368385469634472),
  ('guatemala', 0.024791489818640215),
  ('prague', 0.024791489818640215)],
 9: [('theatre', 0.09697693841712489),
  ('tv', 0.057553591602389126),
  ('thee', 0.04935435506558178),
  ('14', 0.04268947832942847),
  ('scene', 0.04268947832942847),
  ('show', 0.03879077536684996),
  ('became', 0.03489207240427145),
  ('2010', 0.031356257210758784),
  ('1948', 0.02800961590086755),
  ('shall', 0.02800961590086755)],
 10: [('bounce', 0.09496723674222363),
  ('hit', 0.08140048863619169),
  ('skiing', 0.06549927562413661),
  ('game', 0.04422967337356311),
  ('ball', 0.0358940764113322),
  ('slope', 0.0358940764113322),
  ('snow', 0.03305865607491147),
  ('like', 0.026199710249654645),
  ('on', 0.02518389393909512),
  ('mammal', 0.02037062974608549)],
 11: [('mythology', 0.07736811366874036),
  ('queens', 0.07736811366874036),
  ('heroines', 0.06505579567035331),
  ('helen', 0.06109686806780588),
  ('reigned', 0.04709039382404133),
  ('barbara', 0.04709039382404133),
  ('queen', 0.03559715558096456),
  ('her', 0.029917896788246915),
  ('blanchett', 0.026724771134772708),
  ('blanche', 0.026724771134772708)],
 12: [('sportsmen', 0.06935135189056496),
  ('athletes', 0.06935135189056496),
  ('espn', 0.06635264207487492),
  ('sports', 0.06381726905140027),
  ('sport', 0.03981158524492495),
  ('soccer', 0.033768769255398054),
  ('steals', 0.033768769255398054),
  ('player', 0.033768769255398054),
  ('jordan', 0.031101235649423294),
  ('championships', 0.01916447403743569)],
 13: [('mexico', 0.15544478004645904),
  ('kingdom', 0.06528979038618471),
  ('islands', 0.06528979038618471),
  ('resort', 0.04634693939914059),
  ('exile', 0.03955137880541564),
  ('world', 0.03776328778469071),
  ('island', 0.03454328445476867),
  ('country', 0.03124453703691364),
  ('divers', 0.028558824055786518),
  ('madeira', 0.028558824055786518)],
 14: [('music', 0.5820134937487705),
  ('entertainment', 0.5042800797690494),
  ('1997', 0.14565000268451125),
  ('harps', 0.14565000268451125),
  ('mozart', 0.14565000268451125),
  ('abc', 0.14565000268451125),
  ('composer', 0.14565000268451125),
  ('wolfgang', 0.14565000268451125),
  ('espn', 0.10085601595380989),
  ('tv', 0.07481966908310586)],
 15: [('meaning', 0.06728556694063323),
  ('from', 0.05820249860782086),
  ('mean', 0.0546048183704309),
  ('re', 0.04975451978103575),
  ('becomes', 0.047230912194261274),
  ('origins', 0.047230912194261274),
  ('north', 0.041277552748139754),
  ('word', 0.03316967985402383),
  ('germanic', 0.030989362273300264),
  ('compass', 0.030989362273300264)],
 16: [('animal', 0.09328677422447676),
  ('anatomy', 0.09328677422447676),
  ('dog', 0.06275293564662399),
  ('skeletal', 0.04542347722850004),
  ('cord', 0.04542347722850004),
  ('kennel', 0.04183529043108266),
  ('shepherd', 0.025778761537081637),
  ('lions', 0.025778761537081637),
  ('dogs', 0.025778761537081637),
  ('mascots', 0.025778761537081637)],
 17: [('voice', 0.10344206764493322),
  ('train', 0.10344206764493322),
  ('musical', 0.07589240591898394),
  ('trains', 0.07589240591898394),
  ('band', 0.05691930443923795),
  ('singer', 0.040405024091558474),
  ('butthead', 0.024897436356326713),
  ('tedder', 0.024897436356326713),
  ('willie', 0.024897436356326713),
  ('voiced', 0.024897436356326713)],
 18: [('language', 0.9923461363263916),
  ('know', 0.27015015404318443),
  ('syllabus', 0.15331579229948553),
  ('policy', 0.15331579229948553),
  ('curriculum', 0.15331579229948553),
  ('course', 0.13507507702159222),
  ('greek', 0.09859364646580564),
  ('about', 0.08581712499786615),
  ('everlast', 0.0),
  ('everett', 0.0)],
 19: [('country', 0.07284440634891866),
  ('african', 0.058661176306520055),
  ('exiled', 0.054027289356712464),
  ('exile', 0.04610560729317023),
  ('rajaraja', 0.03329142918503114),
  ('kalahari', 0.03329142918503114),
  ('africa', 0.03329142918503114),
  ('lanka', 0.03329142918503114),
  ('botswana', 0.03329142918503114),
  ('morocco', 0.03329142918503114)],
 20: [('science', 0.22271070759130288),
  ('gases', 0.09209197049439624),
  ('ph', 0.06666042762104551),
  ('decay', 0.03783116952844448),
  ('iodine', 0.03783116952844448),
  ('helium', 0.03783116952844448),
  ('photosynthesis', 0.03783116952844448),
  ('compounds', 0.03783116952844448),
  ('dioxide', 0.03783116952844448),
  ('atoms', 0.03783116952844448)],
 21: [('company', 0.11821051153731309),
  ('industry', 0.08346704768591162),
  ('business', 0.08027772327569249),
  ('firm', 0.07079797140442075),
  ('store', 0.0652053492236185),
  ('partnered', 0.04017931108538241),
  ('electronic', 0.04017931108538241),
  ('housewares', 0.04017931108538241),
  ('rockets', 0.04017931108538241),
  ('accutron', 0.04017931108538241)]}

In [33]:
# saving most effective model

topic_model_combined_22_4.save("22-4-model")

In [35]:
# importing new testing dataset
new_df = pd.read_csv('jeopardy_combined.csv', engine="python")
new_df.head()

   Show Number  ...                                       Q_A_Combined
0         4680  ...  For the last 8 years of his life, Galileo was ...
1         4680  ...  No. 2: 1912 Olympian; football star at Carlisl...
2         4680  ...  The city of Yuma in this state has a record av...
3         4680  ...  In 1963, live on "The Art Linkletter Show", th...
4         4680  ...  Signer of the Dec. of Indep., framer of the Co...

[5 rows x 8 columns]

In [37]:
# defining new variable with total docs of 5000
testing = new_df["Q_A_Combined"]
testing_docs = testing.loc[:5000]

In [38]:
# fitting 22_4 model into new data to see how it performs: 

topics, _ = topic_model_combined_22_4.fit_transform(testing_docs)
topic_model_combined_22_4.get_topic_info()

    Topic  Count                                    Name
0      -1   1881                      -1_was_his_from_he
1       0    214                       0_it_your_you_can
2       1    211                   1_archive_jpg_2009_05
3       2    209                 2_wrote_novel_book_poem
4       3    195                  3_her_she_ballet_queen
5       4    191             4_island_sea_planet_islands
6       5    177              5_bird_fish_species_animal
7       6    176     6_president_kennedy_amendment_nixon
8       7    152  7_instrument_symphony_musical_composer
9       8    150              8_war_battle_film_military
10      9    142               9_library_museum_room_art
11     10    137         10_african_river_country_africa
12     11    133                11_played_tv_he_baseball
13     12    130       12_country_emperor_minh_president
14     13    126                   13_god_he_darwin_king
15     14    122                     14_nba_win_won_game
16     15    114               15_meat_food_chicken_dish
17     16    101        16_highest_nobel_arctic_einstein
18     17     96           17_company_000_bureau_billion
19     18     95             18_state_railroad_park_name
20     19     90              19_fruit_flower_peach_tree
21     20     85           20_cheese_french_pasta_coffee
22     21     74                         21_you_or_we_it

In [39]:
topic_model_combined_22_4.topics

{-1: [('was', 0.016134720382434603),
  ('his', 0.013701418717281926),
  ('from', 0.01315353863623927),
  ('he', 0.012243063218269063),
  ('by', 0.011445828310780073),
  ('as', 0.010232966488224682),
  ('name', 0.008567823777639715),
  ('who', 0.007871218355545002),
  ('be', 0.007375611580859525),
  ('her', 0.007127261618597031)],
 0: [('it', 0.0335428335751567),
  ('your', 0.0217685844488914),
  ('you', 0.020382234804293447),
  ('can', 0.014536838353686266),
  ('frog', 0.01304893552892824),
  ('some', 0.01235307548770589),
  ('are', 0.012288579045731697),
  ('brain', 0.011996048636933756),
  ('hormone', 0.011187272605483179),
  ('bones', 0.010609340216920463)],
 1: [('archive', 0.07408139552471617),
  ('jpg', 0.0654802750941685),
  ('2009', 0.02076871342357267),
  ('05', 0.019375030904200622),
  ('wmv', 0.0192650238151954),
  ('2007', 0.01607870585219377),
  ('07', 0.01596247060329176),
  ('2010', 0.015913964495701222),
  ('2008', 0.015606530532176314),
  ('ha', 0.014658785632025165)],
 2: [('wrote', 0.03401355779859443),
  ('novel', 0.0191843680221508),
  ('book', 0.01912320354146183),
  ('poem', 0.0160216742181013),
  ('author', 0.013703120015822),
  ('allan', 0.01187045353897191),
  ('poet', 0.011570682110947295),
  ('poe', 0.011110206461269102),
  ('shelley', 0.01017692204830048),
  ('edgar', 0.009892044615809926)],
 3: [('her', 0.035998860861028076),
  ('she', 0.0336317360489728),
  ('ballet', 0.030280595205545182),
  ('queen', 0.02784048422395141),
  ('dance', 0.019453026236105685),
  ('opera', 0.014878478013034489),
  ('princess', 0.013621056674178044),
  ('girl', 0.01245585321443445),
  ('lady', 0.011775787024378682),
  ('elizabeth', 0.011675191435009752)],
 4: [('island', 0.028410733246914455),
  ('sea', 0.01768862338605438),
  ('planet', 0.0153528139941571),
  ('islands', 0.014611753257707711),
  ('lake', 0.014304500122044107),
  ('canal', 0.013116523247482774),
  ('river', 0.01204825388854377),
  ('water', 0.011667064261531267),
  ('lakes', 0.010930436039568978),
  ('city', 0.010700233088743545)],
 5: [('bird', 0.04172119565331283),
  ('fish', 0.02643981143383808),
  ('species', 0.026325144176527683),
  ('animal', 0.0198043007776315),
  ('type', 0.016883861405951713),
  ('dog', 0.0168438787800856),
  ('breed', 0.014027459214892719),
  ('birds', 0.014027459214892719),
  ('creature', 0.013217447987174174),
  ('salmon', 0.011689549345743932)],
 6: [('president', 0.034363847261954225),
  ('kennedy', 0.01940372222777033),
  ('amendment', 0.018900570342968572),
  ('nixon', 0.015861080381525186),
  ('supreme', 0.014700443600086667),
  ('government', 0.013738281404162282),
  ('fdr', 0.013595211755593016),
  ('congress', 0.013296993143528895),
  ('secretary', 0.013039992332854324),
  ('presidential', 0.012232689653451659)],
 7: [('instrument', 0.02314598147121848),
  ('symphony', 0.02314598147121848),
  ('musical', 0.020343499609116272),
  ('composer', 0.017244058785318078),
  ('sang', 0.015682936501312132),
  ('beethoven', 0.012104894271745763),
  ('sound', 0.011881075200561976),
  ('mozart', 0.011703917539824452),
  ('munich', 0.01137629569473199),
  ('german', 0.011202097500937237)],
 8: [('war', 0.0339602817159413),
  ('battle', 0.03031041535483218),
  ('film', 0.01962292670489965),
  ('military', 0.017423545083844964),
  ('army', 0.016347100554097722),
  ('pirate', 0.016008546971302176),
  ('pulitzer', 0.013975515572005192),
  ('witness', 0.013975515572005192),
  ('played', 0.01167860406642343),
  ('civil', 0.009684080695330947)],
 9: [('library', 0.030200844245023048),
  ('museum', 0.022650633183767286),
  ('room', 0.01823103643853265),
  ('art', 0.01694150023565014),
  ('sculptor', 0.01566433408107818),
  ('oldest', 0.015626602661599414),
  ('hall', 0.014521285916271548),
  ('chair', 0.014250705738360242),
  ('painting', 0.013997313444810875),
  ('building', 0.01318809690652032)],
 10: [('african', 0.03076784934153278),
  ('river', 0.028506326193809443),
  ('country', 0.02846739584418056),
  ('africa', 0.02464533815928183),
  ('nile', 0.02112457556509871),
  ('ottoman', 0.016010394919136108),
  ('rivers', 0.01504672264793429),
  ('westernmost', 0.012520598457537072),
  ('riverthe', 0.012520598457537072),
  ('bangladesh', 0.012520598457537072)],
 11: [('played', 0.04522334372298616),
  ('tv', 0.023901694559020237),
  ('he', 0.02361271939339663),
  ('baseball', 0.01774080768106585),
  ('league', 0.015551798436316506),
  ('actor', 0.015192306402939755),
  ('dodgers', 0.012898752823794192),
  ('yankees', 0.012122371573228055),
  ('abc', 0.011571520309557819),
  ('outfielder', 0.010087203065598321)],
 12: [('country', 0.032365139618479755),
  ('emperor', 0.026328793824241865),
  ('minh', 0.024064615158453245),
  ('president', 0.02137121129909075),
  ('vietnam', 0.019643767852119885),
  ('korea', 0.0162101296936593),
  ('king', 0.016041108854651296),
  ('dictator', 0.015040384474033277),
  ('caesar', 0.014247816701214625),
  ('communist', 0.01296810375492744)],
 13: [('god', 0.04139504946293567),
  ('he', 0.027752058219028868),
  ('darwin', 0.019590227604285772),
  ('king', 0.01869773653951458),
  ('charles', 0.018004237571903458),
  ('son', 0.015745371507772003),
  ('his', 0.015589087940274087),
  ('prophet', 0.012742151365221442),
  ('father', 0.012352922932365146),
  ('lord', 0.011465123601619125)],
 14: [('nba', 0.035758884788887474),
  ('win', 0.029914653713209307),
  ('won', 0.029492251237304683),
  ('game', 0.02670240465734024),
  ('sport', 0.022554696940796495),
  ('golf', 0.022229976925469234),
  ('player', 0.020002072319379997),
  ('score', 0.016274829187964916),
  ('jordan', 0.012186001945522237),
  ('playing', 0.011969322221804342)],
 15: [('meat', 0.03734569659421721),
  ('food', 0.03684771999452818),
  ('chicken', 0.027976897986795538),
  ('dish', 0.026798341814202317),
  ('butter', 0.024887343013113333),
  ('pizza', 0.02171818000981132),
  ('eat', 0.019336922889793377),
  ('bread', 0.01886609002532405),
  ('breakfast', 0.01646028995046186),
  ('cake', 0.012872429568744589)],
 16: [('highest', 0.021934442774924595),
  ('nobel', 0.018525728886282903),
  ('arctic', 0.01796366309927071),
  ('einstein', 0.01796366309927071),
  ('temperature', 0.016882422810982272),
  ('mountains', 0.014622961849949729),
  ('mountain', 0.014105212478107176),
  ('electricity', 0.014048111469356596),
  ('physicist', 0.013472747324453034),
  ('degrees', 0.013026460221824614)],
 17: [('company', 0.056395260119482524),
  ('000', 0.0223461824963259),
  ('bureau', 0.01926991157074647),
  ('billion', 0.018730498680823528),
  ('department', 0.017879368288954353),
  ('co', 0.017716211217349124),
  ('patent', 0.01558592248819149),
  ('edison', 0.014452433678059854),
  ('million', 0.014069148501064893),
  ('fortune', 0.014047874010617646)],
 18: [('state', 0.03908754132006655),
  ('railroad', 0.028140126989936644),
  ('park', 0.026507377867821414),
  ('name', 0.023774389769306833),
  ('wyoming', 0.014070063494968322),
  ('lincoln', 0.012842281033162657),
  ('franklin', 0.01265995140292681),
  ('train', 0.012048871706811369),
  ('started', 0.012048871706811369),
  ('army', 0.012048871706811369)],
 19: [('fruit', 0.04522147002347331),
  ('flower', 0.04015662835116382),
  ('peach', 0.026498088327552103),
  ('tree', 0.02479159765153613),
  ('plants', 0.021924731203340982),
  ('vegetable', 0.021924731203340982),
  ('mauve', 0.021198470662041682),
  ('flowers', 0.019285413982132425),
  ('varieties', 0.015077521255389165),
  ('purple', 0.014751569930837847)],
 20: [('cheese', 0.04688166947673551),
  ('french', 0.04517000736292001),
  ('pasta', 0.02810171917329888),
  ('coffee', 0.02810171917329888),
  ('italian', 0.02596199559614159),
  ('swiss', 0.01686103150397933),
  ('wine', 0.016496523607825036),
  ('france', 0.014438911772402706),
  ('term', 0.013947983920647923),
  ('cuisine', 0.013520511087873452)],
 21: [('you', 0.04843923890037047),
  ('or', 0.03921688562300504),
  ('we', 0.03221948375848126),
  ('it', 0.03122583579701988),
  ('like', 0.02377708081520272),
  ('word', 0.020286183939989315),
  ('are', 0.017576677280918326),
  ('tooth', 0.017522454817892597),
  ('dirty', 0.016566169185562023),
  ('happens', 0.015887673731666312)]}